module.exports = {
  helpCmdPerPage: 10,
  lyricsMaxResults: 5,
  adminId: "436963335414480897",
  token: process.env.token || "",
  clientId: process.env.clientId || "",
  clientSecret: process.env.clientSecret || "",
  port: 4200,
  scopes: ["identify", "guilds", "applications.commands"],
  serverDeafen: true,
  defaultVolume: 100,
  supportServer: "",
  Issues: "",
  permissions: 277083450689,
  disconnectTime: 1,
  twentyFourSeven: true,
  autoQueue: false,
  autoPause: true,
  debug: false,
  cookieSecret: "biscotto",
  website: "https://sgabello.jesgran.repl.co",
  nodes: [
    { "identifier": "INZEWORLD-NODE (RU)", "password": "saher.inzeworld.com", "host": "85.88.163.80", "port": 3128, "secure": false },
  ],
  embedColor: "#ce965d",
  presence: {
    status: "online",
    activities: [
      {
        name: "Golden Wind OST",
        type: "LISTENING",
      },
    ],
  },
  iconURL: "https://cdn.darrennathanael.com/icons/spinning_disk.gif",
};
